import * as dotenv from 'dotenv';
dotenv.config();
const {PORT, WSS_ADDRESS, WSS_PORT, BASTION_WSS_PORT, REDIS_URI, DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS, NOVU_SECRET_KEY, NOVU_TENANT_KEY,
    SECURITY_MAIL, FRONT_END_URL, SECRET_ACCESS_TOKEN, MQTT_SERVER_HOST, MQTT_LHT_METRICS_USERNAME,
    MQTT_LHT_METRICS_PASSWORD, MQTT_CC_DOOR_USERNAME, MQTT_CC_DOOR_PASSWORD, MQTT_VIP_INDOOR_STORAGE_METRICS_USERNAME,
    MQTT_VIP_INDOOR_STORAGE_METRICS_PASSWORD,
    INFLUX_URL, INFLUX_TOKEN, INFLUX_BUCKET, INFLUX_ORG, PROJECT_OWNER, PROJECT_ADMIN, PROJECT_MEMBER,
    COPCART_ADMIN, GRAFANA_URL, GRAFANA_AUTH, GRAFANA_TOKEN, SNAPSHOT_ROOT,
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_FROM } = process.env;

export {PORT, WSS_ADDRESS, WSS_PORT, BASTION_WSS_PORT, REDIS_URI, DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS, NOVU_SECRET_KEY, NOVU_TENANT_KEY,
    SECURITY_MAIL, FRONT_END_URL, SECRET_ACCESS_TOKEN, MQTT_SERVER_HOST, MQTT_LHT_METRICS_USERNAME,
    MQTT_LHT_METRICS_PASSWORD, MQTT_CC_DOOR_USERNAME, MQTT_CC_DOOR_PASSWORD, MQTT_VIP_INDOOR_STORAGE_METRICS_USERNAME,
    MQTT_VIP_INDOOR_STORAGE_METRICS_PASSWORD,
    INFLUX_URL, INFLUX_TOKEN, INFLUX_BUCKET, INFLUX_ORG, PROJECT_OWNER, PROJECT_ADMIN, PROJECT_MEMBER,
    COPCART_ADMIN, GRAFANA_URL, GRAFANA_AUTH, GRAFANA_TOKEN, SNAPSHOT_ROOT,
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_FROM };
